spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google

  datasource:
    url: jdbc:postgresql://localhost:5432/despesas
    username: dev_user
    password: dev_pass

  jpa:
    hibernate:
      ddl-auto: create-drop  # Atualiza o banco no dev
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


server:
  port: 8080

